### ISSUE TITLE
Test fails because "Invalid hook call."

### ISSUE THREAD

**Issue by massimeddu-sonic** [toomuchdesign/next-page-tester#147] opened 2021-02-12 17:11 UTC
## 💬 Questions and Help
Hello,

I'm facing an issue that I'm not able to solve with the following test:

```typescript
import { screen } from '@testing-library/react';
import { getPage } from 'next-page-tester';

describe('Home page', () => {
  it('renders without crashing', async () => {
    const { render } = await getPage({
      route: '/',
      dotenvFile: '.env.local'
    });
    render();
    expect(screen.getByRole('heading', { name: 'HomePage' })).toBeInTheDocument();
  });
```

I got this error

```
Home page › renders without crashing

    Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app
    See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

      22 |
      23 | export default function Popup(): JSX.Element {
    > 24 |   const [prefix, setPrefix] = useState<string>('');

```

with this component:

```typescript
[...]

export default function Popup(): JSX.Element {
  const [prefix, setPrefix] = useState<string>('');
[...]
```

Do you know I can solve this?

Thank you,

**Comment by toomuchdesign** [comment] 2021-02-12 18:05
Hi @massimeddu-sonic,
would you make sure that your issue is not the same as #118?

**Comment by massimeddu-sonic** [comment] 2021-02-12 18:17
Hi Andrea,

it looks like a different issue. I had that #118 issue and I've solved it using the patched version of jest, but then this issue arise.

**Comment by Meemaw** [comment] 2021-02-12 18:21
Are you using some context providers from third party libraries?

**Comment by massimeddu-sonic** [comment] 2021-02-12 18:26
Yes,

this is how it looks my `_app.tsx`

```typescript
import React from 'react';

import type { AppProps } from 'next/app';

import 'lib/styles/global.scss';
import { SWRConfig } from 'swr';

import CookiesPopup from '~/components/cookiespopup';
import { DownloadAppContextProvider } from '~/contexts/download-app.context';
import fetch from '~/lib/fetch';

const webApp = ({ Component, pageProps }: AppProps): JSX.Element => {
  return (
    <>
      <SWRConfig
        value={{
          fetcher: fetch,
        }}
      >
        <DownloadAppContextProvider>
          <Component {...pageProps} />
        </DownloadAppContextProvider>
        <CookiesPopup />
      </SWRConfig>
    </>
  );
};

export default webApp;
```

DownloadAppContextProvider is a custom context provider and SWRConfig is from a library.

**Comment by Meemaw** [comment] 2021-02-12 18:31
Can you pass nonIsolatedModules option to getPage with ['swr'].

It might work for you but this is currently a bit hacky and hopefully were gonna have a proper solution soon so that it wont be needed anymore.

**Comment by massimeddu-sonic** [comment] 2021-02-15 08:28
> Can you try passing `nonIsolatedModules` option to the getPage with `['swr']` value:.
> 
> It might work for you but this is currently a bit hacky and hopefully we're gonna have a proper solution soon so that it wont be needed anymore.

Unfortunately it didn't solve the issue.

**Comment by toomuchdesign** [comment] 2021-02-15 08:38
v0.20.0 is on the launching pad and should solve at least one reason why `swr` can't render.

**Comment by toomuchdesign** [comment] 2021-02-15 22:03
@massimeddu-sonic v.020.0 released!

**Comment by fracture91** [comment] 2021-02-16 03:08
I'm running into a similar issue with [emotion](https://github.com/emotion-js/emotion)/[theme-ui](https://github.com/system-ui/theme-ui).  I have the jest patch installed.  Here is a stack trace - not sure how useful it is.  The offending hook call is here: https://github.com/emotion-js/emotion/blob/b59084b7cbfeab11c2a986033952d481d0b9fcf4/packages/react/src/context.js#L39

```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app
    See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

      10 | class MyDocument extends Document {
      11 |   static async getInitialProps(ctx: DocumentContext) {
    > 12 |     const initialProps = await Document.getInitialProps(ctx)
         |                                         ^
      13 |     const styles = extractCritical(initialProps.html)
      14 | 
      15 |     return {

      at resolveDispatcher (node_modules/react/cjs/react.development.js:1476:13)
      at Object.useContext (node_modules/react/cjs/react.development.js:1484:20)
      at EmotionGlobal (node_modules/@emotion/react/dist/emotion-element-cb6e9ca7.cjs.dev.js:43:25)
      at processChild (node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
      at resolve (node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
      at ReactDOMServerRenderer.render (node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
      at ReactDOMServerRenderer.read (node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
      at Object.renderToString (node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
      at Object.renderPage (node_modules/next-page-tester/dist/_document/render.js:47:35)
      at Function.getInitialProps (node_modules/next/pages/_document.tsx:86:38)
      at getInitialProps (pages/_document.tsx:12:41)
      at node_modules/next-page-tester/dist/_document/fetchDocumentData.js:13:47
      at Object.executeAsIfOnServer (node_modules/next-page-tester/dist/server.js:29:22)
      at Object.fetchDocumentData [as default] (node_modules/next-page-tester/dist/_document/fetchDocumentData.js:13:21)
      at node_modules/next-page-tester/dist/_document/render.js:58:63
      at Object.executeAsIfOnServer (node_modules/next-page-tester/dist/server.js:29:22)
      at Object.serverRenderDocument (node_modules/next-page-tester/dist/_document/render.js:31:21)
      at getPage (node_modules/next-page-tester/dist/getPage.js:68:49)
      at Object.<anonymous> (__tests__/pages/blog/blog.tsx:17:26)
```

For some reason, I was able to get around the error on v0.19.0 by passing `nonIsolatedModules: ["react"]` in the `getPage` call.  I have no idea why that works, since `"react"` is isolated by default by next-page-tester.

After that fix, I ran into trouble similar to #142 - [it seemed like emotion was getting confused about whether it was running on the server or the client](https://github.com/toomuchdesign/next-page-tester/issues/142#issuecomment-772784929) after I put its packages in `nonIsolatedModules`.  

Luckily, v0.20.0 seems to have solved that problem (thank you!).  But the `nonIsolatedModules` option was removed, reintroducing the "invalid hook call" error.  I patched in something similar with [patch-package](https://www.npmjs.com/package/patch-package) and now my tests pass:

```diff
diff --git a/node_modules/next-page-tester/dist/utils.js b/node_modules/next-page-tester/dist/utils.js
index 59e916c..172ade2 100644
--- a/node_modules/next-page-tester/dist/utils.js
+++ b/node_modules/next-page-tester/dist/utils.js
@@ -80,6 +80,7 @@ exports.useMountedState = useMountedState;
 // @NOTE: This modules still need to preserve their identity between client and server
 // because we import them within our code which serves both environments :(
 const nonIsolatedModules = [
+    "react",
     'react',
     'next/dist/next-server/lib/head-manager-context',
     'next/dist/next-server/lib/router-context',
```

Again, I have no idea why that fixes it and this might introduce bugs of its own, but maybe this is helpful in the search for a long-term fix.

**Comment by massimeddu-sonic** [comment] 2021-02-16 08:29
> @massimeddu-sonic v.020.0 released!

Unfortunately the new release didn't solve the issue. This is the full stacktrace:

```
Home page › renders without crashing

    Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app
    See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

      26 |
      27 | export function DownloadAppContextProvider({ children }: DownloadAppContextProviderProp): JSX.Element {
    > 28 |   const [showAndroid, setShowAndroid] = useState<boolean>(false);
         |                                         ^

      at resolveDispatcher (node_modules/react/cjs/react.development.js:1476:13)
      at useState (node_modules/react/cjs/react.development.js:1507:20)
      at DownloadAppContextProvider (src/contexts/download-app.context.tsx:28:41)
      at processChild (node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
      at resolve (node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
      at ReactDOMServerRenderer.render (node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
      at ReactDOMServerRenderer.read (node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
      at Object.renderToString (node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
      at node_modules/next-page-tester/dist/makeRenderMethods.js:16:75
      at Object.executeAsIfOnServerSync (node_modules/next-page-tester/dist/server.js:39:16)
      at serverRenderToString (node_modules/next-page-tester/dist/makeRenderMethods.js:16:28)
      at serverRender (node_modules/next-page-tester/dist/makeRenderMethods.js:21:26)
      at render (node_modules/next-page-tester/dist/makeRenderMethods.js:39:30)
      at Object.<anonymous> (test/pages/index.test.tsx:13:5)
```

**Comment by toomuchdesign** [comment] 2021-02-16 18:26
@fracture91 Did you just patch the `nonIsolatedModules` array? Weird that duplicating `react` entry has any effect at all.

@massimeddu-sonic, hard to say what's going wrong. Would you mind setting up a reproduction repo?

**Comment by tomalexhughes** [comment] 2021-02-16 19:40
I don't have anything too useful to add but the patch provided by @fracture91 fixed one of my tests that was throwing an `Invalid hook call.` when using `useQuery` from `@apollo/client`.

I do still have the following error which seems to also be logged by the `useQuery` call.

```
    Warning: An update to Home inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
```

**Comment by fracture91** [comment] 2021-02-16 19:53
> @fracture91 Did you just patch the `nonIsolatedModules` array? Weird that duplicating `react` entry has any effect at all.

Yup, that's the entirety of my patch file.  If I delete it, my tests fail.

I finally managed to get a "minimal" reproduction working with just emotion, no theme-ui: https://github.com/fracture91/next-page-tester-hook-error

Tests fail as-is, but pass with my patch

**Comment by toomuchdesign** [comment] 2021-02-16 20:13
Thanks @fracture91 for setting up the repo. It's one of the funniest bug I've met :) I hope to get back to you soon(ish) with some good news.

Cheers!

**Comment by toomuchdesign** [comment] 2021-02-17 22:29
Partial good news: it seems that if we move the `nonIsolatedModules` block out of `executeWithFreshModules` function, tests do green again.

We'll have to refactor a bit `executeWithFreshModules` around this finding.

**Comment by toomuchdesign** [comment] 2021-02-21 00:33
Hi @fracture91, while putting together a PR for the issue you reproduced, I noticed that your page files (document, app and page) don't import react. Would you mind checking whether the issue was caused by the missing react imports?

If so, we might try to improve error messages.

**Comment by toomuchdesign** [comment] 2021-02-21 11:30
This issue seems to show up only when `next-page-tester` is consumed as package. We already run our tests against a local dist folder and tests remains green.

I'm definitely considering fixing this but I'm currently unsure how to test against possible regression bugs. I found out that npm does't allow installing the published version of a package as dev dependency of the package itself.

**Comment by Meemaw** [comment] 2021-02-21 11:45
> This issue seems to show up only when `next-page-tester` is consumed as package. We already run our tests against a local dist folder and tests remains green.
> 
> I'm definitely considering fixing this but I'm currently unsure how to test against possible regression bugs. I found out that npm does't allow installing the published version of a package as dev dependency of the package itself.

One way would be using a `monorepo` setup.

**Comment by toomuchdesign** [comment] 2021-02-21 14:32
> One way would be using a monorepo setup.

Vercel doesn't pay us enough 😄

**Comment by massimeddu-sonic** [comment] 2021-02-22 11:04
> 
> ```diff
> diff --git a/node_modules/next-page-tester/dist/utils.js b/node_modules/next-page-tester/dist/utils.js
> index 59e916c..172ade2 100644
> --- a/node_modules/next-page-tester/dist/utils.js
> +++ b/node_modules/next-page-tester/dist/utils.js
> @@ -80,6 +80,7 @@ exports.useMountedState = useMountedState;
>  // @NOTE: This modules still need to preserve their identity between client and server
>  // because we import them within our code which serves both environments :(
>  const nonIsolatedModules = [
> +    "react",
>      'react',
>      'next/dist/next-server/lib/head-manager-context',
>      'next/dist/next-server/lib/router-context',
> ```
> 
> Again, I have no idea why that fixes it and this might introduce bugs of its own, but maybe this is helpful in the search for a long-term fix.

This fixed also my issue.

**Comment by toomuchdesign** [comment] 2021-02-22 11:18
Hi @massimeddu-sonic,
we're working on a fix. We'll release soonish in the upcoming days.

**Closed** 2021-02-22 12:57 UTC

**Comment by Nikolay-Borzov-EPAM** [comment] 2021-11-12 09:22
I see this error on `next-page-tester 0.30.0`, `jest 27.3.1`

when jest config contains
```
resetModules: true,
```

**Comment by toomuchdesign** [comment] 2021-11-12 13:55
Hi @Nikolay-Borzov-EPAM, since `next-page-tester` manipulates the import registry to [simulate server/client rendering](https://github.com/toomuchdesign/next-page-tester/blob/master/docs/a-note-about-client-and-server-renders.md), resetting modules could interfere with it.

**Comment by Nikolay-Borzov-EPAM** [comment] 2021-11-12 14:15
No problem with that. I just noticed I needed `resetMocks` instead of `resetModules`
