### ISSUE TITLE
act() warnings when using React Hook Form

### ISSUE THREAD

**Issue by osadi** [toomuchdesign/next-page-tester#180] opened 2021-03-03 08:34 UTC
## 🐛 Bug Report
When a form that's using `form.register()` from [React Hook Form](https://react-hook-form.com/) is conditionally rendered within a test, `act()` warnings are printed in the console.

A workaround seems to be to:

```
import { render } from '@testing-library/react'

const { page } = getPage({route: '/'})
render(page)
```
In the reproduction repo both variants (render from npt, render from tl) are used.

## To Reproduce

1. Create a page with a form. Set a `ref` on an input in the form using `form.register()`.
2. Mount and unmount the form within the page with a toggle switch
In a test:
1. Render the page with `render()` from `getPage()`
2. act on the toggle switch to mount the form
3. console logs an `act()` warning

## Expected behavior
No warnings

## Link to repl or repo
https://github.com/osadi/npt-react-hook-form

Should work with `npm i && npm run test` 

## Run `npx envinfo --preset jest`

```bash
npx: installed 1 in 0.964s

  System:
    OS: Linux 5.4 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  npmPackages:
    jest: ^26.6.3 => 26.6.3 

```

**Comment by toomuchdesign** [comment] 2021-03-03 10:07
Hi @osadi, thanks for reporting.
Have you patched `jest` as explained in the docs?
https://github.com/toomuchdesign/next-page-tester#optional-patch-jest

**Comment by Meemaw** [comment] 2021-03-03 10:59
@toomuchdesign I might be wrong but I don't think its related to patching jest. I've seen similar warnings with `react-hook-form` in my project as well.

**Comment by osadi** [comment] 2021-03-03 11:06
I have now :)

```
➜  hook-form git:(main) ✗ npm install
> with-jest@0.1.0 postinstall /code/hook-form
> patch-package
```

And

```
➜  hook-form git:(main) ✗ tree patches
patches
└── jest-runtime+26.6.3.patch
```
Still the same `act()` warnings though..

**Comment by Meemaw** [comment] 2021-03-03 11:12
It might be as simple as wrapping our `hydrate`  into react's act test utility, but I would like to do it on a reproducer without external dependency so we have a stable test for it.

**Comment by toomuchdesign** [comment] 2021-03-05 15:16
Hi @osadi,
I've checked out our repro (thanks for putting up one 🙌 ), and realised what you had written already: the `act` warning is issued after `next-page-tester` has happened.

At first glance I'd be inclined to think that the issue might not be related to `next-page-tester` since once the page is rendered in JSDOM we're mostly out of its realm. Have you ensured it's not something lying between `testing-library` and `react-hook-form`?

You might find out by rendering the page component directly with `testing-library`. `react-hook-form` discussion page reports quite a few `act()` issues which might be relevant for your case.

**Comment by Meemaw** [comment] 2021-03-06 07:22
Ah, I though you are receiving `act` warning after just after `rendering`  -- not after performing client interactions. Those are out of scope of the library and its a known issue with `react-hook-form`, e.g. see https://github.com/testing-library/user-event/issues/457 for example.

**Closed** 2021-03-09 07:58 UTC
